ITEM_POOl = ['sword', 'glove', 'cloak', 'rod', 'tear', 'belt', 'bow', 'vest', 'dupe']

TFT_CHAMPIONS = {
    "Ahri": {"cost": 4, "traits": ["Blossom", "Spellweaver"], "role": "magic caster"},
    "Akali": {"cost": 1, "traits": ["Inferno", "Adaptor", "Ravager"], "role": "attack fighter"},
    "Alistar": {"cost": 2, "traits": ["Elderwood", "Brawler"], "role": "magic tank"},
    "Alune": {"cost": 5, "traits": ["Attuned", "Lunar", "Spellweaver"], "role": "magic caster"},
    "Amumu": {"cost": 4, "traits": ["Inferno", "Juggernaut"], "role": "magic tank"},
    "Ancient Sentinel": {"cost": 4, "traits": ["Riftbeast", "Vanguard", "Invoker"], "role": "magic tank"},
    "Aphelios": {"cost": 4, "traits": ["Lunar", "Rapidfire"], "role": "attack marksman"},
    "Ashe": {"cost": 5, "traits": ["Blossom", "Hunter"], "role": "attack caster"},
    "Azir": {"cost": 3, "traits": ["Eldritch", "Executioner", "Summoner"], "role": "magic marksman"},
    "Brambleback": {"cost": 4, "traits": ["Riftbeast", "Ravager"], "role": "attack fighter"},
    "Caitlyn": {"cost": 2, "traits": ["Coven", "Hunter"], "role": "attack specialist"},
    "Camille": {"cost": 1, "traits": ["Coven", "Ravager"], "role": "attack fighter"},
    "Cassiopeia": {"cost": 3, "traits": ["Coven", "Spellweaver"], "role": "magic caster"},
    "Cinderling": {"cost": 1, "traits": ["Riftbeast", "Hunter"], "role": "attack caster"},
    "Diana": {"cost": 3, "traits": ["Lunar", "Ravager", "Vanguard"], "role": "magic fighter"},
    "Draven": {"cost": 5, "traits": ["Bounty Seeker"], "role": "attack marksman"},
    "Elise": {"cost": 2, "traits": ["Coven", "Vanguard"], "role": "magic tank"},
    "Ezreal": {"cost": 4, "traits": ["Elderwood", "Executioner"], "role": "attack caster"},
    "Fiddlesticks": {"cost": 3, "traits": ["Flora Fatalis", "Defender", "Spellweaver"], "role": "magic tank"},
    "Gnar": {"cost": 5, "traits": ["Elderwood", "Sprykin", "Brawler"], "role": "attack specialist"},
    "Gromp": {"cost": 2, "traits": ["Riftbeast", "Adaptor"], "role": "magic caster"},
    "Hecarim": {"cost": 3, "traits": ["Elderwood", "Vanguard"], "role": "magic tank"},
    "Ivern": {"cost": 5, "traits": ["Greenfather"], "role": "magic caster"},
    "Karma": {"cost": 1, "traits": ["Spellweaver", "Blossom"], "role": "magic caster"},
    "Kayle": {"cost": 2, "traits": ["Solar", "Rapidfire"], "role": "attack specialist"},
    "Kennen": {"cost": 5, "traits": ["Inferno", "Executioner"], "role": "magic assassin"},
    "Kha'Zix": {"cost": 3, "traits": ["Rival"], "role": "magic assassin"},
    "Kobuko": {"cost": 1, "traits": ["Sprykin", "Brawler"], "role": "magic tank"},
    "Kog'Maw": {"cost": 3, "traits": ["Caustic", "Invoker", "Adaptor"], "role": "attack caster"},
    "Krug": {"cost": 3, "traits": ["Riftbeast", "Brawler"], "role": "attack tank"},
    "LeBlanc": {"cost": 2, "traits": ["Elderwood", "Spellweaver"], "role": "magic caster"},
    "Leona": {"cost": 1, "traits": ["Solar", "Defender"], "role": "magic tank"},
    "Lillia": {"cost": 4, "traits": ["Fae", "Defender"], "role": "magic tank"},
    "Lux (Blossom)": {"cost": 5, "traits": ["Avatar", "Blossom"], "role": "magic caster"},
    "Lux (Coven)": {"cost": 5, "traits": ["Avatar", "Coven"], "role": "magic caster"},
    "Lux (Elderwood)": {"cost": 5, "traits": ["Avatar", "Elderwood"], "role": "magic caster"},
    "Lux (Eldritch)": {"cost": 5, "traits": ["Avatar", "Eldritch"], "role": "magic caster"},
    "Lux (Fae)": {"cost": 5, "traits": ["Avatar", "Fae"], "role": "magic caster"},
    "Lux (Inferno)": {"cost": 5, "traits": ["Avatar", "Inferno"], "role": "magic caster"},
    "Lux (Lunar)": {"cost": 5, "traits": ["Avatar", "Lunar"], "role": "magic caster"},
    "Lux (Primal)": {"cost": 5, "traits": ["Avatar", "Primal"], "role": "magic caster"},
    "Lux (Solar)": {"cost": 5, "traits": ["Avatar", "Solar"], "role": "magic caster"},
    "Malphite": {"cost": 4, "traits": ["Eldritch", "Monolith"], "role": "magic tank"},
    "Mama Beak": {"cost": 3, "traits": ["Riftbeast", "Summoner", "Rapidfire"], "role": "attack marksman"},
    "Maokai": {"cost": 5, "traits": ["Old Growth", "Juggernaut"], "role": "magic tank"},
    "Master Yi": {"cost": 3, "traits": ["Blossom", "Adaptor"], "role": "attack specialist"},
    "Morgana": {"cost": 4, "traits": ["Coven", "Invoker"], "role": "magic fighter"},
    "Murkwolf": {"cost": 2, "traits": ["Riftbeast", "Ravager"], "role": "attack assassin"},
    "Nidalee": {"cost": 4, "traits": ["Primal", "Adaptor"], "role": "magic marksman"},
    "Ornn": {"cost": 1, "traits": ["Elderwood", "Defender"], "role": "magic tank"},
    "Pebbles": {"cost": 1, "traits": ["Riftbeast", "Invoker"], "role": "magic caster"},
    "Rakan": {"cost": 1, "traits": ["Fae", "Juggernaut", "Vanguard"], "role": "magic tank"},
    "Rammus": {"cost": 3, "traits": ["Sprykin", "Defender"], "role": "attack tank"},
    "Rek'Sai": {"cost": 1, "traits": ["Eldritch", "Brawler"], "role": "magic tank"},
    "Rengar": {"cost": 3, "traits": ["Rival"], "role": "attack fighter"},
    "Scuttlecrab": {"cost": 2, "traits": ["Riftbeast", "Juggernaut"], "role": "attack tank"},
    "Sejuani": {"cost": 2, "traits": ["Solar", "Juggernaut"], "role": "magic tank"},
    "Sett": {"cost": 4, "traits": ["Blossom", "Brawler"], "role": "attack tank"},
    "Shen": {"cost": 2, "traits": ["Inferno", "Defender"], "role": "magic tank"},
    "Sivir": {"cost": 4, "traits": ["Primal", "Hunter"], "role": "attack caster"},
    "Soraka": {"cost": 4, "traits": ["Flora Fatalis", "Executioner"], "role": "magic caster"},
    "Taric": {"cost": 5, "traits": ["Emerald Aspect", "Vanguard"], "role": "magic tank"},
    "Teemo": {"cost": 2, "traits": ["Sprykin", "Invoker"], "role": "magic caster"},
    "The Elder Dragon": {"cost": 5, "traits": ["Riftbeast", "Apex Predator"], "role": "attack fighter"},
    "Tristana": {"cost": 3, "traits": ["Fae", "Sprykin", "Hunter"], "role": "attack marksman"},
    "Varus": {"cost": 1, "traits": ["Inferno", "Rapidfire"], "role": "attack caster"},
    "Veigar": {"cost": 1, "traits": ["Eldritch", "Sprykin", "Spellweaver"], "role": "magic caster"},
    "Vi": {"cost": 3, "traits": ["Primal", "Juggernaut"], "role": "attack tank"},
    "Warwick": {"cost": 2, "traits": ["Eldritch", "Ravager"], "role": "attack fighter"},
    "Xayah": {"cost": 1, "traits": ["Elderwood", "Fae", "Rapidfire"], "role": "attack marksman"},
    "Yorick": {"cost": 1, "traits": ["Blossom", "Juggernaut", "Summoner"], "role": "attack tank"},
    "Yunara": {"cost": 2, "traits": ["Blossom", "Executioner"], "role": "attack caster"},
    "Zyra": {"cost": 4, "traits": ["Thornmaiden", "Summoner"], "role": "magic caster"},
}